# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import product_of_three_numbers_pb2 as product__of__three__numbers__pb2


class CalculateProductOfTripletStub(object):
    """The Server service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CalculateMaxTriplet = channel.unary_unary(
                '/proto.CalculateProductOfTriplet/CalculateMaxTriplet',
                request_serializer=product__of__three__numbers__pb2.Request.SerializeToString,
                response_deserializer=product__of__three__numbers__pb2.Response.FromString,
                )


class CalculateProductOfTripletServicer(object):
    """The Server service definition.
    """

    def CalculateMaxTriplet(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalculateProductOfTripletServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CalculateMaxTriplet': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateMaxTriplet,
                    request_deserializer=product__of__three__numbers__pb2.Request.FromString,
                    response_serializer=product__of__three__numbers__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.CalculateProductOfTriplet', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CalculateProductOfTriplet(object):
    """The Server service definition.
    """

    @staticmethod
    def CalculateMaxTriplet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.CalculateProductOfTriplet/CalculateMaxTriplet',
            product__of__three__numbers__pb2.Request.SerializeToString,
            product__of__three__numbers__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
